FROM openpai/standard:python_3.6-pytorch_1.2.0-gpu

RUN branch_name=pai-for-edu
RUN wget https://raw.githubusercontent.com/microsoft/pai/${branch_name}/contrib/edu-examples/pytorch_cifar10/src/cifar.py
RUN wget https://raw.githubusercontent.com/microsoft/pai/${branch_name}/contrib/edu-examples/pytorch_cifar10/src/init.sh
RUN bash init.sh
